version: "3.9"

services:
  app:
    image: hasandocker4/ollama-api:latest
    deploy:
      replicas: 3
      resources:
        limits:
          cpus: "0.5"
          memory: 512M
      restart_policy:
        condition: any
    environment:
      - PORT=3000
      - OLLAMA_BASE_URL=http://host.docker.internal:11434
    ports:
      - "3000:3000"
    networks:
      - backend

networks:
  backend:
    driver: overlay
